### ISSUE TITLE
"Wikipedia" should be translatable

### ISSUE THREAD

**Issue by jhsoby** [jdlrobson/wikipedia-year-in-review#10]
"Wikipedia" on the main page should be translatable, preferrably together with the "year-in-review" message. Wikipedia [has many names](https://store.wikimedia.org/cdn/shop/files/Wiki383.jpg?v=1690222096&width=1680), and some languages may need to place the Wikipedia name after the "year-in-review" message (think "Year-in-review on Wikipedia").

**Comment by jdlrobson** [comment]
Since the app supports different projects, we might want to rethink the name e.g. Wiki

**Comment by jhsoby** [comment]
Ah, yeah, true, I didn't even think about that
