### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by Ainali** [jdlrobson/wikipedia-year-in-review#2]
Please pick a license for this project. I was about to fork it to make a contribution, but as there is no license file, I wouldn't be compelled.

**Comment by jdlrobson** [comment]
https://github.com/jdlrobson/wikipedia-year-in-review/blob/cd1f072ec73e8be85bbf087526b5e26f50df8b42/package.json#L10 the license is in the package.json

I can add a license file and am also open to changing license if you have any strong preferences

**Comment by Ainali** [comment]
The license is OSI approved, so all good! I was just so used to the GitHub conventions, it didn't even occur to me to look in the json file. :smiley: 
It's good enough for me, so feel free to close the issue, but it may be easier for others too to just add a License file that GitHub recognizes and puts in the sidebar.

**Comment by jdlrobson** [comment]
Done!
