### ISSUE TITLE
Updating strings for translation

### ISSUE THREAD

**Issue by jnpoJuwan** [jdlrobson/wikipedia-year-in-review#9]
The work is very nice however, the strings given to translation on translatewiki.net are too English-centric to do anything well. Firstly, it splits the strings in two in places in the middle of a sentence or phrase. Most critically, it doesn't work at all for languages that put the number after the noun.

I believe that this could be solved with using formatted strings with `$1`. However, I am just a translator, not a great programmer.

**Comment by jdlrobson** [comment]
Hi @jnpoJuwan thanks for filing the issue! @jhsoby raised a similar concern and a possible solution. Hoping to have this easier to translate by end of week.
